# Generated by Django 6.0.3 on 2026-03-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_course_name_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='course_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='plan_title',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
